[package]
name = "e2p"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
image = "0.25.5"
nshare = "0.10.0"
ndarray-linalg = { version = "0.17.0", features = ["openblas-system"] }
opencv = "0.92"